### ISSUE TITLE
Implement Factory reset with barebone firmware

### ISSUE THREAD

**Issue by nicolabortignon** [SeedLabs-it/smartknob-firmware#36]
Pressing a combination of the physical buttons on the device should reset the device to a barebone firmware, with the only functionalities of booting as an access point (so people can upload a working firmware). 
A QRcode should be displayed to allow easy access to the AP. 
The smartknob should publish, via a local webserver, a page to upload a firmware. 

This is to avoid bricking the device. 

There are opportunities to have an even better experience, but will talk about that in a different issue.  

Ref to partitioning for esp32: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/partition-tables.html

**Comment by carlhampuswall** [comment]
Factory reset to "factory" flashed firmware implemented in #100 
Is this good enough to close issue?

**Comment by carlhampuswall** [comment]
Will close when release script is updated to use recovery/barebones firmware.
